### ISSUE TITLE
Write urls without quotes

### ISSUE THREAD

**Issue by martinpesout** [visionappscz/standardcss#4]
In `README.md` you have written that you write urls without quoters. I totally agree with this rule. But if you check `.stylelintrc` there is written rule `"function-url-quotes": "always",`. And this mean that you have to write quotes when defining URLs. 

If you change it to `"function-url-quotes": "never",`, everything will be fixed again.

**Comment by adamkudrna** [comment]
We decided to discontinue this project in favour of [stylelint-config-visionapps](https://github.com/visionappscz/stylelint-config-visionapps) which is a more strict fork of [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard).
