### ISSUE TITLE
Really long box-shadow definition

### ISSUE THREAD

**Issue by martinpesout** [visionappscz/standardcss#5]
I have this CSS property:

```
box-shadow: rgba(#000, .15) 0 1px 3px 0,
	rgba(#000, .05) 0 0 0 1px,
	rgba(#3DB6F2, .6) 0 0 0 1px;
```

With stylelint rule `"value-list-comma-space-after": "always",` I have to rewrite it to:

```
box-shadow: rgba(#000, .15) 0 1px 3px 0, rgba(#000, .05) 0 0 0 1px, rgba(#3DB6F2, .6) 0 0 0 1px;
```

From my point of view this will make `box-shadow` property really long on one line. What will be better is to allow both: writing everything on one line or on multiline. And always keep rule that we need to have space after comma. Changing stylelint rule `value-list-comma-space-after` to this `"value-list-comma-space-after": "always-single-line",` will do this magic 🌹

**Comment by adamkudrna** [comment]
We decided to discontinue this project in favour of [stylelint-config-visionapps](https://github.com/visionappscz/stylelint-config-visionapps) which is a more strict fork of [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard).
