### ISSUE TITLE
More strict rules

### ISSUE THREAD

**Issue by martinpesout** [visionappscz/standardcss#6]
@adamkudrna after your talk in Prague, I tried to implement it in our project https://app.becontentking.com and also did some comparison with this article http://www.creativenightly.com/2016/02/How-to-lint-your-css-with-stylelint/

I think that rules can be more strict. I'll write you down my list of additional rules which works also for us:

- `"max-empty-lines": 3` - sometimes I need to have more empty lines in my comments of SCSS. It will improve readability. But maximum 3 empty lines is enough
- ` "selector-list-comma-space-before": "never", "declaration-block-no-duplicate-properties": [true, {"ignore": ["consecutive-duplicates"]}]` - prevent duplicates in SCSS
- `"block-no-empty": true` - disallow empty blocks in SCSS
- `"color-no-invalid-hex": true` - disallow invalid hex color
- `"declaration-colon-space-before": "never"` - require a single space or disallow whitespace before the colon of declarations
- `"media-feature-colon-space-after": "always", "media-feature-colon-space-before": "never", "media-feature-name-no-vendor-prefix": true` - add stylelint rules for media queries
- `"number-leading-zero": "never"` - disallow a leading zero for fractional numbers less than 1
- `"number-no-trailing-zeros": true` - disallow trailing zeros in numbers
- `"property-no-vendor-prefix": true, "value-no-vendor-prefix": true` - disallow vendor prefixes in SCSS. This job is done usually by `autoprefixer`.

**Comment by adamkudrna** [comment]
We decided to discontinue this project in favour of [stylelint-config-visionapps](https://github.com/visionappscz/stylelint-config-visionapps) which is a more strict fork of [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard).
